### ISSUE TITLE
Loader function example from docs not working

### ISSUE THREAD

**Issue by john-waczak** [JuliaParallel/DTables.jl#32]
Following the example [here](https://docs.juliahub.com/Dagger/0a2f8/0.14.0/dtable/#Loader-function-and-file-list) I encounter the following error: 

```julia
julia> d = DTable(CSV.File, files)
ERROR: MethodError: no method matching DTable(::Type{CSV.File}, ::Vector{String})

Closest candidates are:
  DTable(::Any, ::Any, ::Any)
   @ DTables ~/.julia/packages/DTables/DZcii/src/table/dtable.jl:13
  DTable(::Function, ::Vector{String}; tabletype)
   @ DTables ~/.julia/packages/DTables/DZcii/src/table/dtable.jl:142
  DTable(::Vector{Union{Dagger.EagerThunk, Dagger.Chunk}}, ::Any, ::Union{Nothing, Tables.Schema})                                                              
   @ DTables ~/.julia/packages/DTables/DZcii/src/table/dtable.jl:13
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[58]:1
```

I think the issue is that DTable expects a function. The following runs without issue: 
```julia
julia> d = DTable(x->CSV.File(x), files)
DTable with 3 partitions
Tabletype: unknown (use `tabletype!(::DTable)`)
```

For reference, here is the status of my environment:
```
  [6e4b80f9] BenchmarkTools v1.3.2
  [336ed68f] CSV v0.10.11
  [13f3f980] CairoMakie v0.10.6
  [20c56dc6] DTables v0.3.1
⌅ [d58978e5] Dagger v0.16.3
  [a93c6f00] DataFrames v1.6.0

```

**Comment by jpsamaroo** [comment]
Yeah, we should change the signature to accept `Base.Callable` instead. Do you mind filing a PR with a short test (just do the same thing you show here)?

**Comment by john-waczak** [comment]
Happy to submit a PR! I hadn't come across `Base.Callable` before and found [this thread](https://github.com/JuliaLang/julia/issues/43491) after some googling. Is it better to just remove the type specification for `loader_function` in the definition?

**Comment by jpsamaroo** [comment]
Yeah that should be fine!

**Comment by john-waczak** [comment]
Great! I'll give this a go and will submit a PR later today.

**Comment by john-waczak** [comment]
@jpsamaroo submitted a PR with the update.
